
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 34;
  public static final int CORABRE = 37;
  public static final int PRY = 32;
  public static final int PRBAR = 23;
  public static final int PRX = 31;
  public static final int CHAR = 7;
  public static final int EJE = 30;
  public static final int DOUBLE = 8;
  public static final int RESTA = 11;
  public static final int PUNTOCOMA = 35;
  public static final int IGUAL = 43;
  public static final int COLUMN = 21;
  public static final int PARCIERRA = 41;
  public static final int ARROBA = 39;
  public static final int TITULO = 27;
  public static final int SUMA = 10;
  public static final int PRLINE = 25;
  public static final int MIN = 20;
  public static final int ID = 45;
  public static final int MEDIANA = 16;
  public static final int DECIMAL = 44;
  public static final int EOF = 0;
  public static final int ARREGLO = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 42;
  public static final int CADENA = 46;
  public static final int VALUES = 29;
  public static final int MODULO = 14;
  public static final int MODA = 17;
  public static final int FLECHA = 36;
  public static final int VARIANZA = 18;
  public static final int PARABRE = 40;
  public static final int GRAPH = 22;
  public static final int END = 3;
  public static final int MEDIA = 15;
  public static final int CORCIERRA = 38;
  public static final int EXEC = 26;
  public static final int LABEL = 28;
  public static final int DIVISION = 13;
  public static final int MAX = 19;
  public static final int PRPIE = 24;
  public static final int VAR = 4;
  public static final int HISTOGRAM = 33;
  public static final int PRINT = 6;
  public static final int CONSOLE = 5;
  public static final int MULTIPLICACION = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "END",
  "VAR",
  "CONSOLE",
  "PRINT",
  "CHAR",
  "DOUBLE",
  "ARREGLO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN",
  "GRAPH",
  "PRBAR",
  "PRPIE",
  "PRLINE",
  "EXEC",
  "TITULO",
  "LABEL",
  "VALUES",
  "EJE",
  "PRX",
  "PRY",
  "HISTOGRAM",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "FLECHA",
  "CORABRE",
  "CORCIERRA",
  "ARROBA",
  "PARABRE",
  "PARCIERRA",
  "COMA",
  "IGUAL",
  "DECIMAL",
  "ID",
  "CADENA"
  };
}

